version: '3.8'

services:
  php:
    build:
      context: .
    volumes:
      - ./app:/var/www/html
    networks:
      - mynetwork

  nginx:
    image: nginx:1.22
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    ports:
      - "8080:80"
    networks:
      - mynetwork

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: tickets
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
